### ISSUE TITLE
create pull request feature can't work

### ISSUE THREAD

**Issue by trend-yafang-qiu** [kbrashears5/github-action-file-sync#15]
Push changes to [***github.com/xxxxx.git]
  To https://github.com/xxxxxx.git
   + 616fb80...86323c4 staging -> staging (forced update)
  Creating pull request from [staging] into [main]
  {
    "message": "Bad credentials",
    "documentation_url": "https://docs.github.com/enterprise/3.2/rest"
  }

**Comment by ghost** [comment]
#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @kbrashears5 to notify them. This will be looked at soon!

**Comment by kbrashears5** [comment]
@QiuYafang did you add a PAT?

```yaml
          TOKEN: ${{ secrets.ACTIONS }}
```

**Comment by ghost** [comment]
This issue has not received a response in a timely manner. If you still think there is a problem, please leave a comment to avoid the issue from automatically closing.

**Comment by ghost** [comment]
This issue has been automatically closed. Please create a new issue if it still exists.

**Comment by pandu-malik** [comment]
i also have something similar to this issue

```
jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master

      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            ${{ github.event.inputs.repo-org }}/${{ github.event.inputs.repo-name }}
          FILES: |
            ${{ github.event.inputs.repo-name }}/${{ github.event.inputs.file-to-sync }}=.github/workflows/${{ github.event.inputs.file-to-sync }}
          TOKEN: ${{ secrets.REPO_TOKEN }}
          PULL_REQUEST_BRANCH_NAME: pipeline
```

i do have `pipeline` branch on my target repo, but the error only said:
`Unexpected input(s) 'PULL_REQUEST_BRANCH_NAME', valid inputs are ['entryPoint', 'args', 'REPOSITORIES', 'FILES', 'TOKEN']`
