### ISSUE TITLE
PULL_REQUEST_BRANCH_NAME invalid input

### ISSUE THREAD

**Issue by tomdaniels** [kbrashears5/github-action-file-sync#20]
Hi, I am using latest version of the file-sync github action https://github.com/marketplace/actions/file-sync

The documentation mentions that I can configure a `PULL_REQUEST_BRANCH_NAME` to raise a PR against on the target repository. The file-sync is working as expected, creating a new branch and pushing the changes to the target repository, though no PR is raised. 

I am using the latest version of the workflow which should `create pull requests` judging from the changelog entry in version 2.1.0:
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/28723321/227814236-91fe4e21-7e2d-4b5d-a312-b74e3962cf24.png">

Instead I receive the below error:
```
Unexpected input(s) 'PULL_REQUEST_BRANCH_NAME', valid inputs are ['entryPoint', 'args', 'REPOSITORIES', 'FILES', 'TOKEN', 'PULL_REQUEST']
```

my file is as follows: 
```yaml
name: sdk_changelog_sync

on:
  workflow_call:
      inputs:
        node-version:
          required: true
          type: string
        ref:
          required: false
          default: ''
          type: string

jobs:
  sync_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: sync_changelog
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            tomdaniels/playground@changelog-sync
          PULL_REQUEST_BRANCH_NAME: master
          FILES: |
            packages/charts-embed-dom/CHANGELOG.md=CHANGELOG.md
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

Any insight you can offer into why this may be happening would be greatly appreciated, I can not see any usage examples in the documentation to confirm if this is user error or in fact an issue with the workflow itself. 

Thank you in advance please let me know if there's any other information that would be helpful
